// auto generated by scripts/i18n.ts
import React from 'react';

/* eslint-disable */
export interface I18nRes {
  n: {
    returnType: '{n}' | 'en: {n}';

    valuesType: {
      n: any;
    };
  };
  c: {
    returnType: '<s>{c}</s>' | 'en: <s>{c}</s>';

    valuesType: {
      c: any;

      s: (chunks: React.ReactNode) => React.ReactNode;
    };
  };
}

export type I18nResKeys = keyof I18nRes;

export type I18nTranslate = <T extends I18nResKeys>(
  key: T,
  values: I18nRes[T]['valuesType'],
) => I18nRes[T]['returnType'];
