import { globSync } from 'glob';
import path from 'path';
import { getTsTypesFromRes } from 'typed-icu-message';
import fs from 'fs';

(async () => {
  const jsons = globSync('src/i18n/*.json');
  const all: any = {};
  for (const json of jsons) {
    const locale = path.basename(json).replace('.json', '');
    all[locale] = require(path.resolve(json));
  }
  const typedCode = getTsTypesFromRes(all, {
    reactI18next: '@yiminghe/react-i18next',
  });
  fs.writeFileSync(
    path.resolve('src/i18n/types.ts'),
    `
  // auto generated by scripts/i18n.ts
  ${typedCode}`,
  );
})();
